#!/bin/bash
adduser --system --no-create-home honeytrap-agent

mkdir -p /var/lib/honeytrap-agent
mkdir -p /var/log/honeytrap-agent

chown -R honeytrap-agent /var/lib/honeytrap-agent
chown -R honeytrap-agent /var/log/honeytrap-agent
