FROM golang:1.10 AS go

FROM centos
RUN yum -y update 
RUN yum -y install rpm-build git
RUN yum -y groupinstall 'Development Tools'

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

COPY --from=go /usr/local/go /usr/local/go

WORKDIR /build

CMD /bin/sh ./build.sh

