FROM golang:latest AS go

FROM centos
RUN yum -y update 
RUN yum -y install rpm-build git
RUN yum -y groupinstall 'Development Tools'

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

COPY --from=go /usr/local/go /usr/local/go
COPY --from=go /usr/local/bin/go-wrapper /usr/local/bin/go-wrapper

WORKDIR /build

CMD /bin/sh ./build.sh

