FROM golang:1.10 AS go

FROM debian
RUN apt update -y 
RUN apt install -y debhelper git

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

COPY --from=go /usr/local/go /usr/local/go

WORKDIR /build

CMD /bin/sh ./build.sh
